#!/usr/bin/env bash
alias i='sudo apt install -y'
alias r='sudo apt remove'
alias s='apt-cache search'
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'
alias upgradable='sudo apt list --upgradable'
alias distupgrade='sudo apt-get dist-upgrade'
alias autoremove='sudo apt-get autoremove'
alias purge='sudo apt-get purge'
alias show='apt-cache show'
alias list='dpkg-query -L'
alias apt-origin='apt-file search'
