#!/usr/bin/env bash
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gds='git diff --staged'
alias gl='git log --graph --decorate=auto --branches'
alias gp='git push'
alias grc='git rebase --continue'
alias grh='git reset HEAD'
alias grs='git rebase --skip'
alias gs='git status'
alias gsec='git secret'
